config/routes.rb
TimebookingCegekaBe::Application.routes.draw do
  match 'account/login' => 'account#login', :as => 'login'
  match 'account/logout' => 'account#logout', :as => 'logout'
  match 'home' => 'home#index', :as => 'home'
  match 'timesheet/add' => 'timesheet#add', :as => 'time_add'
  match 'reports/generate' => 'reports#generate', :as => 'generate_reports'

  root :to => 'home#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  attr_accessible :comment, :date, :issue, :project, :time

  # Gets the user timesheet data and orders in accordingly
  def self.get_user_data (username)
	return Timesheet.where(:username => username).order("date DESC")
  end

  def self.get_report_data (username)
  	return Timesheet.where(:username => username).order("project DESC").order("date DESC")
  end

  # Gets the dates available for reporting
  def self.get_user_report_dates (username) 
  	return Timesheet.where(:username => username).order("project DESC").order("date DESC").select([:date])
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def login
  	if request.post?
  		logger.debug "Login form POST request"

  		username = params[:username]
  		password = params[:password]

  		# Encode password
  		password = Digest::SHA1.hexdigest(password)

  		# Get user account
  		account = Account.find_by_username_and_password(username, password)

  		if account.blank?
  			logger.debug "Login details incorrect for user [#{username}]"
  			flash[:error] = "Login details are incorrect."
  		else
  			logger.debug "Login details are correct for user [#{username}]"
  			flash[:notice] = "You have successfully logged in."

  			# Set session data
  			session[:logged_in] = true
  			session[:username] = username

  			redirect_to home_path
  		end
  	end
  end

  def logout
  	reset_session
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if session[:logged_in].nil?
  		logger.debug "Not logged in"

  		redirect_to login_path
  	else
  		logger.debug "Logged in"

  		@timesheets = Timesheet.get_user_data session[:username]
  		@report_dates = Timesheet.get_user_report_dates session[:username]
  	end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def generate
  	# Get parameter
  	@report_date = params[:timesheet][:report_date]
  	logger.debug @report_date

  	# Reference data
  	@timesheets = Timesheet.where(:username => session[:username], :date => @report_date)

  	# Feed data to view
  	if @timesheets.empty?
  		flash[:notice] = "There is no data available on the selected date."
  	end
  end
end

app/controllers/timesheet_controller.rb
class TimesheetController < ApplicationController
  def add
  	if request.post?
  		# Get parameters
  		date = Date.parse(params[:timesheet_date].to_a.sort.collect{|c| c[1]}.join("-"))

  		# Get time
  		hours = params[:timesheet_time][:'work_time(4i)']
  		minutes = params[:timesheet_time][:'work_time(5i)']
  		time = "#{hours}:#{minutes}"

  		project = params[:project]
  		issue = params[:issue]
  		comment = params[:comment]

  		logger.debug time

  		# Create new timesheet entry
  		timesheet = Timesheet.new
  		timesheet.date = date
  		timesheet.time = time
  		timesheet.project = project
  		timesheet.issue = issue
  		timesheet.comment = comment
  		timesheet.username = session[:username]
  		timesheet.save

  		redirect_to home_path
  	end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Transform achievo code to project name.
	def achievo_code_to_project_name code
		case code
		when 'P01185'
			return 'Marketing'
		when 'P01193'
			return 'Ordertool'
		when 'P01285'
			return 'Smartspot'
		when 'P01299'
			return 'Realspeed'
		when 'P01209'
			return "BRE On Line"
		when '1060558'
			return "SEPA DD"
		when 'P01305'
			return "Popcorn"
		when 'Competence Centre'
			return 'Competence Centre'
		when 'Sun Phase 3'
			return 'Sun Phase 3'
		when 'Testing'
			return 'Testing'
		when 'Refactorings'
			return 'Refactorings'
		end
	end

	def achievo_code_to_camis_wo code
		case code
		when 'P01185'
			return 'TLN-000.100'
		when 'P01193'
			return 'TLN-000.100'
		when 'P01285'
			return 'TLN-000.100'
		when 'P01299'
			return 'TLN-000.100'
		when 'P01209'
			return 'TLN-000.100'
		when '1060558'
			return 'TLN-000.100'
		when 'P01305'
			return 'TLN-000.100'
		when 'Competence Centre'
			return 'OPLE914.050'
		when 'Sun Phase 3'
			return 'TLN-001.030'
		else
			return 'TLN-000.001'
		end
	end

	def achievo_code_to_achievo_fulltext code
		case code
		when 'P01185'
			return 'P01185: 2013-Product Marketing Mobile'
		when 'P01193'
			return 'P01193: 2013-Operational Development'
		when 'P01285'
			return 'P01285: 2013-IT_RSC - Smartspot Home Delivery'
		when 'P01299'
			return 'P01299: 2013-IT_RMD - NTL Realspeed'
		when 'P01209'
			return 'P01209: 2013-BRE On Line'
		when '1060558'
			return '1060558: 2013-IT SEPA direct debit-1060558'
		when 'P01305'
			return 'P01305: 2013-IT_RMD - Popcorn'
		else
			return 'Unbookable in Achievo'
		end
	end

	def concat_projects entries
		output = []

		entries.each do |e|
			output.push(e.project)
		end

		return output.join(' + ')
	end

	def concat_time entries
		hours = 0
		minutes = 0

		entries.each do |e|
			splitted = e.time.split(/:/)

			hours += splitted.first.to_i
			minutes += splitted.second.to_i
		end

		if minutes <= 60
			hours += minutes / 60
			minutes = minutes % 60
		end

		return "#{hours}:#{minutes}"
	end

	def concat_work_orders entries
		output = []

		entries.each do |e|
			output.push(achievo_code_to_camis_wo e.project)
		end

		return output.join(' + ')
	end

	def concat_issues entries
		output = []

		entries.each do |e|
			output.push(e.issue)
		end

		return output.join(' + ')
	end

	def date_performed_camis date
		date = date.to_time.strftime('%a/%m/%d')
	end

	def date_performed_achievo date
		date = date.to_time.strftime('%A %d/%B/%Y')
	end

	def date_started_jira date
		date = date.to_time.strftime('%d/%B/%y')

		return "#{date} 12:00 PM"
	end

	def link_to_jira issue
		link_to issue, "http://jira.tln-dev.cegeka.be/jira/browse/#{issue}", :target => "_blank"
	end

	def time_to_jira time
		time = time.split(/:/)
		hours = time.first.to_i
		minutes = time.second.to_i

		if minutes >= 60
			hours += minutes / 60
			minutes = minutes % 60
		end

		output = "#{hours}h #{minutes}m"
	end

	def time_to_camis time
		time = time.split(/:/)
		hours = time.first.to_i
		minutes = time.second.to_i

		if minutes <= 60
			hours += minutes / 60
			minutes = minutes % 60
		end

		if minutes < 10
			minutes = "#{minutes}0"
		end

		return "#{hours}.#{minutes}"
	end
end


# ['Marketing', 'P01185'], 
# ['Ordertool', 'P01193'],
# ['Smartspot', 'P01285'],
# ['Realspeed', 'P01299']

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/timesheet_helper.rb
module TimesheetHelper
end

app/views/home/index.html.erb
<div id="user-metadata-box" class="box">
	Logged in as: <%= session[:username] %> &yen; <a href="/account/logout">Logout</a>
</div>

<h1 class="title">Universal Timebooking Cegeka</h1>

<div class="clear"></div>

<!-- New timesheet -->
<div id="new-timesheet">
	<h2>New Timesheet</h2>

	<%= form_tag time_add_path, :class => 'box' do %>
		<table>
			<tr>
				<td><%= label_tag :work_date %></td>
				<td><%= date_select :timesheet_date, :work_date %></td>
			</tr>

			<tr>
				<td><%= label_tag :work_time %></td>
				<td><%= time_select :timesheet_time, :work_time, {:default => {:hour => "02", :minute => "00"}, :minute_step => 15} %></td>
			</tr>

			<tr>
				<td><%= label_tag :project %></td>
				<td><%= select_tag(:project, options_for_select([
						['Marketing', 'P01185'], 
						['Ordertool', 'P01193'],
						['Smartspot', 'P01285'],
						['Realspeed', 'P01299'],
						['BRE On Line', 'P01209'],
						['Popcorn', 'P01305'],
						['SEPA DD', '1060558'],,
						['Sun Phase 3', 'Sun Phase 3'],
						['Testing', 'Testing'],
						['Refactorings', 'Refactorings'],
						['Competence Centre', 'Competence Centre']
					])) %></td>
			</tr>

			<tr>
				<td><%= label_tag :issue, "Jira Issue" %></td>
				<td><%= text_field_tag :issue %></td>
			</tr>

			<tr>
				<td><%= label_tag :comment %></td>
				<td><%= text_area_tag :comment, "", {:rows => 10} %></td>
			</tr>

			<tr>
				<td colspan="2"><%= submit_tag("Add Timesheet") %></td>
			</tr>
		</table>
	<% end %>
</div>


<!-- Previous timesheets -->
<div id="previous-timesheets">
	<h2>Previous Timesheets</h2>

	<% @timesheets.each do |t| %>
	<div class="box toggable">
		<!-- Display issue and date -->
		<span class="left issue"><strong><%= t.issue %> (<%= t.time %>)</strong></span>
		<span class="right date"><%= t.date.to_time.strftime('%A %B %d') %></span>
		<div class="clear"></div>

		<div class="metadata">
			<span class="project"><strong>Project: </strong> <%= t.project %></span>

			<div>
				<%= simple_format(t.comment) %>
			</div>
		</div>
	</div>
	<% end %>
</div>

<div id="generate-report">
	<h2>Generate Report</h2>

	<p>In order to generate a report, please fill in the form below:</p>

	<%= form_tag generate_reports_path, :class => "box" do %>
	<table>
		<tr>
			<td><%= label_tag :report_date %></td>
			<td><%= collection_select :timesheet, :report_date, @timesheets, :date, :date %></td>
		</tr>

		<tr>
			<td colspan="2"><%= submit_tag "Generate report" %></td>
		</tr>
	</table>
	<% end %>
</div>

<div class="clear"></div>

<script type="text/javascript">
$(document).ready(function(){
	$('#previous-timesheets div').click(function(event) {
		$(this).children('.metadata').toggle(300);
	});
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universal Timebooking Cegeka</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main-content">
	<%= yield %>
</div>

</body>
</html>

app/views/reports/generate.html.erb
<div id="reports">
	<h2 class="right"><a href="/home">Back to timesheet interface</a></h2>

	<h1>Generated Report for <%= @report_date %></h1>

	<div class="clear"></div>

	<p>The report below has been generated based on your <%= @report_date %> work logs.</p>

	<h2>General</h2>
	<table border="1">
		<thead>
			<tr>
				<th>Issue Nr.</th>
				<th>Project</th>
				<th>Time spent</th>
				<th>Comment</th>
			</tr>
		</thead>

		<tbody>
			<% @timesheets.each do |t| %>
			<tr>
				<td><%= t.issue %></td>
				<td><%= achievo_code_to_project_name t.project %> - <%= t.project %></td>
				<td><%= t.time %></td>
				<td class="aleft"><%= simple_format(t.comment) %></td>
			</tr>
			<% end %>
		</tbody>

		<tfoot>
			<tr>
				<td><%= concat_issues @timesheets %></td>
				<td><%= concat_projects @timesheets %></td>
				<td><%= concat_time @timesheets%></td>
				<td>Total hours worked</td>
			</tr>
		</tfoot>
	</table>

	<h2>Jira</h2>
	

	<table border="1">
		<thead>
			<tr>
				<th>Issue Nr.</th>
				<th>Time Spent</th>
				<th>Date Started</th>
				<th>Work Description</th>
			</tr>
		</thead>

		<tbody>
			<% @timesheets.each do |t| %>
			<tr>
				<td><%= link_to_jira t.issue %></td>
				<td><%= time_to_jira t.time %></td>
				<td><%= date_started_jira t.date %></td>
				<td class="aleft"><%= simple_format(session[:username] + ":\n\n" + t.comment) %></td>
			</tr>
			<% end %>
		</tbody>

		<tfoot>
			<tr>
				<td><%= concat_issues @timesheets %></td>
				<td><%= time_to_jira concat_time @timesheets%></td>
				<td><%= date_started_jira @timesheets.first.date %></td>
				<td>Total hours worked</td>
			</tr>
		</tfoot>
	</table>

	<h2>Camis</h2>

	<table border="1">
		<thead>
			<tr>
				<th>Work Log</th>
				<th>Description</th>
				<th>Work Performed</th>
				<th>Work time</th>
			</tr>
		</thead>

		<tbody>
			<% @timesheets.each do |t| %>
			<tr>
				<td><%= achievo_code_to_camis_wo t.project %></td>
				<td><%= t.issue %></td>
				<td><%= date_performed_camis t.date %></td>
				<td><%= time_to_camis t.time %></td>
			</tr>
			<% end %>
		</tbody>

		<tfoot>
			<tr>
				<td><%= concat_work_orders @timesheets %></td>
				<td><%= concat_issues @timesheets %></td>
				<td><%= date_performed_camis @timesheets.first.date %></td>
				<td><%= time_to_camis concat_time @timesheets%></td>
			</tr>
		</tfoot>
	</table>

	<h2>Achievo</h2>

	<table border="1">
		<thead>
			<tr>
				<th>Date</th>
				<th>Project</th>
				<th>Remark</th>
				<th>Time</th>
			</tr>
		</thead>

		<tbody>
			<% @timesheets.each do |t| %>
			<tr>
				<td><%= date_performed_achievo t.date %></td>
				<td><%= achievo_code_to_achievo_fulltext t.project %></td>
				<td class="aleft"><%= time_to_jira t.time %>: <%= t.issue %><br /><br /><%= simple_format(t.comment) %></td>
				<td><%= t.time %></td>
			</tr>
			<% end %>
		</tbody>

		<tfoot>
			<tr>
				<td><%= date_performed_achievo @timesheets.first.date %></td>
				<td><%= concat_projects @timesheets %></td>
				<td><%= date_performed_camis @timesheets.first.date %></td>
				<td><%= time_to_camis concat_time @timesheets%></td>
			</tr>
		</tfoot>
	</table>
</div>

<script type="text/javascript">
	$(document).ready(function(){

		$('td').zclip({
	        copy : function(e) {
	        	return $(e.currentTarget).text();
	        } 
	    });

	});
</script>

app/views/timesheet/add.html.erb
<h1>Timesheet#add</h1>
<p>Find me in app/views/timesheet/add.html.erb</p>